import type { BoardLayout } from "@/engine/types";

/**
 * Disposizione `classic` (task F1-01): 100 caselle, 7 scale, 6 serpenti, geometrie decorative.
 *
 * Le posizioni sono una proposta ispirata a `docs/reference/board/boardReference.png` e vanno
 * riviste dal proprietario (vedi "Ancora aperte" in docs/decisions.md). Il validatore dei vincoli
 * è in `src/engine/board-validation.ts`, il test in `src/content/boards/boards.test.ts`.
 *
 * Quantità per tipo: 35 domande, 12 sfide, 10 imprevisti, 10 monete, 3 stelle, 28 libere, partenza e arrivo.
 */
export const classic: BoardLayout = {
  id: "classic",
  name: "Classico",
  cells: [
    { n: 1, kind: "start" },
    { n: 2, kind: "question", category: "tastes", illustration: "tastes-bottle" },
    { n: 3, kind: "event" },
    { n: 4, kind: "free" },
    { n: 5, kind: "free" },
    { n: 6, kind: "coins", sign: "gain" },
    { n: 7, kind: "question", category: "memories", illustration: "memories-letter" },
    { n: 8, kind: "question", category: "future", illustration: "future-ring" },
    { n: 9, kind: "free" },
    { n: 10, kind: "question", category: "deep", illustration: "deep-mirror" },
    { n: 11, kind: "challenge" },
    { n: 12, kind: "event" },
    { n: 13, kind: "question", category: "funny", illustration: "funny-eye" },
    { n: 14, kind: "question", category: "tastes", illustration: "tastes-glasses" },
    { n: 15, kind: "star", illustration: "stars-star" },
    { n: 16, kind: "event" },
    { n: 17, kind: "coins", sign: "loss" },
    { n: 18, kind: "event" },
    { n: 19, kind: "challenge" },
    { n: 20, kind: "question", category: "memories", illustration: "memories-frame" },
    { n: 21, kind: "question", category: "future", illustration: "future-house" },
    { n: 22, kind: "coins", sign: "gain" },
    { n: 23, kind: "free" },
    { n: 24, kind: "question", category: "deep", illustration: "deep-rose" },
    { n: 25, kind: "question", category: "funny", illustration: "funny-toothbrush" },
    { n: 26, kind: "free" },
    { n: 27, kind: "challenge" },
    { n: 28, kind: "question", category: "tastes", illustration: "tastes-vinyl" },
    { n: 29, kind: "challenge" },
    { n: 30, kind: "free" },
    { n: 31, kind: "free" },
    { n: 32, kind: "coins", sign: "loss" },
    { n: 33, kind: "event" },
    { n: 34, kind: "question", category: "memories", illustration: "memories-typewriter" },
    { n: 35, kind: "free" },
    { n: 36, kind: "question", category: "future", illustration: "future-cage" },
    { n: 37, kind: "challenge" },
    { n: 38, kind: "question", category: "deep", illustration: "deep-lock" },
    { n: 39, kind: "event" },
    { n: 40, kind: "question", category: "funny", illustration: "funny-dice" },
    { n: 41, kind: "challenge" },
    { n: 42, kind: "free" },
    { n: 43, kind: "question", category: "tastes", illustration: "tastes-guitar" },
    { n: 44, kind: "free" },
    { n: 45, kind: "coins", sign: "gain" },
    { n: 46, kind: "free" },
    { n: 47, kind: "free" },
    { n: 48, kind: "free" },
    { n: 49, kind: "free" },
    { n: 50, kind: "free" },
    { n: 51, kind: "challenge" },
    { n: 52, kind: "question", category: "memories", illustration: "memories-phone" },
    { n: 53, kind: "star", illustration: "stars-big-star" },
    { n: 54, kind: "coins", sign: "loss" },
    { n: 55, kind: "event" },
    { n: 56, kind: "coins", sign: "gain" },
    { n: 57, kind: "free" },
    { n: 58, kind: "question", category: "future", illustration: "future-map" },
    { n: 59, kind: "free" },
    { n: 60, kind: "free" },
    { n: 61, kind: "free" },
    { n: 62, kind: "question", category: "deep", illustration: "deep-candle" },
    { n: 63, kind: "coins", sign: "loss" },
    { n: 64, kind: "free" },
    { n: 65, kind: "free" },
    { n: 66, kind: "event" },
    { n: 67, kind: "free" },
    { n: 68, kind: "question", category: "funny", illustration: "funny-apple" },
    { n: 69, kind: "free" },
    { n: 70, kind: "question", category: "tastes", illustration: "tastes-cup" },
    { n: 71, kind: "question", category: "memories", illustration: "memories-ticket" },
    { n: 72, kind: "question", category: "future", illustration: "future-key" },
    { n: 73, kind: "coins", sign: "gain" },
    { n: 74, kind: "question", category: "deep", illustration: "deep-moon" },
    { n: 75, kind: "question", category: "funny", illustration: "funny-sock" },
    { n: 76, kind: "question", category: "tastes", illustration: "tastes-ice-cream" },
    { n: 77, kind: "question", category: "memories", illustration: "memories-cassette" },
    { n: 78, kind: "question", category: "future", illustration: "future-plane" },
    { n: 79, kind: "challenge" },
    { n: 80, kind: "star", illustration: "stars-star-cluster" },
    { n: 81, kind: "question", category: "deep", illustration: "deep-roots" },
    { n: 82, kind: "free" },
    { n: 83, kind: "free" },
    { n: 84, kind: "free" },
    { n: 85, kind: "question", category: "funny", illustration: "funny-banana" },
    { n: 86, kind: "challenge" },
    { n: 87, kind: "question", category: "tastes", illustration: "tastes-bread" },
    { n: 88, kind: "challenge" },
    { n: 89, kind: "event" },
    { n: 90, kind: "free" },
    { n: 91, kind: "challenge" },
    { n: 92, kind: "question", category: "memories", illustration: "memories-suitcase" },
    { n: 93, kind: "coins", sign: "loss" },
    { n: 94, kind: "free" },
    { n: 95, kind: "challenge" },
    { n: 96, kind: "event" },
    { n: 97, kind: "question", category: "future", illustration: "future-sprout" },
    { n: 98, kind: "question", category: "deep", illustration: "deep-hourglass" },
    { n: 99, kind: "question", category: "funny", illustration: "funny-alarm" },
    { n: 100, kind: "finish" },
  ],
  ladders: [
    { from: 3, to: 22 },
    { from: 8, to: 26 },
    { from: 20, to: 41 },
    { from: 28, to: 72 },
    { from: 36, to: 57 },
    { from: 51, to: 67 },
    { from: 74, to: 92 },
  ],
  snakes: [
    { from: 17, to: 7 },
    { from: 54, to: 34 },
    { from: 62, to: 18 },
    { from: 87, to: 37 },
    { from: 93, to: 73 },
    { from: 98, to: 79 },
  ],
  decorations: [
    { shape: "circle", cells: [4, 5] },
    { shape: "half-circle", cells: [9] },
    { shape: "diagonal", cells: [23] },
    { shape: "filled", cells: [26] },
  ],
};
