/**
 * Disposizione «La Ripida»: congelata dal seme 11 con `pnpm board:freeze 11 "La Ripida"`.
 *
 * **File generato: non modificare a mano.** Quello che segue è il contenuto della disposizione,
 * scritto come dato: non si rigenera dal seme, quindi non si muove se un giorno cambia il
 * generatore (è tutto il punto del congelamento). Per una variante si congela un seme nuovo.
 *
 * Non entra in partita da sola: la `classic` resta la disposizione offerta finché il proprietario
 * non sceglie quali disposizioni entrano (F7-03).
 */
import type { BoardLayout } from "@/engine/types";

export const laRipida: BoardLayout = {
  id: "la-ripida",
  name: "La Ripida",
  cells: [
    { n: 1, kind: "start" },
    { n: 2, kind: "free" },
    { n: 3, kind: "question", category: "tastes", illustration: "tastes-cup" },
    { n: 4, kind: "free" },
    { n: 5, kind: "challenge" },
    { n: 6, kind: "question", category: "tastes", illustration: "tastes-bread" },
    { n: 7, kind: "question", category: "tastes", illustration: "tastes-bottle" },
    { n: 8, kind: "free" },
    { n: 9, kind: "free" },
    { n: 10, kind: "free" },
    { n: 11, kind: "event" },
    { n: 12, kind: "challenge" },
    { n: 13, kind: "question", category: "tastes", illustration: "tastes-vinyl" },
    { n: 14, kind: "question", category: "tastes", illustration: "tastes-ice-cream" },
    { n: 15, kind: "free" },
    { n: 16, kind: "free" },
    { n: 17, kind: "question", category: "tastes", illustration: "tastes-glasses" },
    { n: 18, kind: "question", category: "tastes", illustration: "tastes-guitar" },
    { n: 19, kind: "question", category: "memories", illustration: "memories-cassette" },
    { n: 20, kind: "question", category: "memories", illustration: "memories-ticket" },
    { n: 21, kind: "event" },
    { n: 22, kind: "free" },
    { n: 23, kind: "question", category: "memories", illustration: "memories-suitcase" },
    { n: 24, kind: "question", category: "memories", illustration: "memories-typewriter" },
    { n: 25, kind: "free" },
    { n: 26, kind: "question", category: "memories", illustration: "memories-letter" },
    { n: 27, kind: "coins", sign: "loss" },
    { n: 28, kind: "question", category: "memories", illustration: "memories-phone" },
    { n: 29, kind: "challenge" },
    { n: 30, kind: "question", category: "memories", illustration: "memories-frame" },
    { n: 31, kind: "question", category: "future", illustration: "future-key" },
    { n: 32, kind: "challenge" },
    { n: 33, kind: "free" },
    { n: 34, kind: "question", category: "future", illustration: "future-ring" },
    { n: 35, kind: "event" },
    { n: 36, kind: "question", category: "future", illustration: "future-cage" },
    { n: 37, kind: "free" },
    { n: 38, kind: "challenge" },
    { n: 39, kind: "coins", sign: "gain" },
    { n: 40, kind: "question", category: "future", illustration: "future-map" },
    { n: 41, kind: "coins", sign: "gain" },
    { n: 42, kind: "event" },
    { n: 43, kind: "question", category: "future", illustration: "future-plane" },
    { n: 44, kind: "question", category: "future", illustration: "future-sprout" },
    { n: 45, kind: "question", category: "future", illustration: "future-house" },
    { n: 46, kind: "coins", sign: "gain" },
    { n: 47, kind: "challenge" },
    { n: 48, kind: "event" },
    { n: 49, kind: "coins", sign: "loss" },
    { n: 50, kind: "free" },
    { n: 51, kind: "free" },
    { n: 52, kind: "event" },
    { n: 53, kind: "challenge" },
    { n: 54, kind: "question", category: "deep", illustration: "deep-candle" },
    { n: 55, kind: "question", category: "deep", illustration: "deep-rose" },
    { n: 56, kind: "free" },
    { n: 57, kind: "star", illustration: "stars-star" },
    { n: 58, kind: "event" },
    { n: 59, kind: "coins", sign: "gain" },
    { n: 60, kind: "challenge" },
    { n: 61, kind: "coins", sign: "loss" },
    { n: 62, kind: "free" },
    { n: 63, kind: "free" },
    { n: 64, kind: "question", category: "deep", illustration: "deep-moon" },
    { n: 65, kind: "star", illustration: "stars-big-star" },
    { n: 66, kind: "free" },
    { n: 67, kind: "free" },
    { n: 68, kind: "free" },
    { n: 69, kind: "question", category: "deep", illustration: "deep-hourglass" },
    { n: 70, kind: "free" },
    { n: 71, kind: "event" },
    { n: 72, kind: "coins", sign: "loss" },
    { n: 73, kind: "coins", sign: "gain" },
    { n: 74, kind: "event" },
    { n: 75, kind: "free" },
    { n: 76, kind: "free" },
    { n: 77, kind: "question", category: "deep", illustration: "deep-roots" },
    { n: 78, kind: "challenge" },
    { n: 79, kind: "question", category: "deep", illustration: "deep-mirror" },
    { n: 80, kind: "question", category: "deep", illustration: "deep-lock" },
    { n: 81, kind: "free" },
    { n: 82, kind: "free" },
    { n: 83, kind: "question", category: "funny", illustration: "funny-banana" },
    { n: 84, kind: "coins", sign: "loss" },
    { n: 85, kind: "challenge" },
    { n: 86, kind: "question", category: "funny", illustration: "funny-apple" },
    { n: 87, kind: "question", category: "funny", illustration: "funny-alarm" },
    { n: 88, kind: "challenge" },
    { n: 89, kind: "free" },
    { n: 90, kind: "question", category: "funny", illustration: "funny-eye" },
    { n: 91, kind: "challenge" },
    { n: 92, kind: "question", category: "funny", illustration: "funny-dice" },
    { n: 93, kind: "free" },
    { n: 94, kind: "star", illustration: "stars-star-cluster" },
    { n: 95, kind: "free" },
    { n: 96, kind: "free" },
    { n: 97, kind: "event" },
    { n: 98, kind: "question", category: "funny", illustration: "funny-toothbrush" },
    { n: 99, kind: "question", category: "funny", illustration: "funny-sock" },
    { n: 100, kind: "finish" },
  ],
  ladders: [
    { from: 16, to: 52 },
    { from: 4, to: 58 },
    { from: 27, to: 77 },
    { from: 55, to: 97 },
    { from: 8, to: 30 },
    { from: 2, to: 42 },
    { from: 51, to: 70 },
  ],
  snakes: [
    { from: 83, to: 61 },
    { from: 15, to: 6 },
    { from: 93, to: 90 },
    { from: 21, to: 20 },
    { from: 74, to: 69 },
    { from: 94, to: 86 },
  ],
  decorations: [
    { shape: "disc", cells: [62, 63] },
    { shape: "crescent", cells: [75] },
    { shape: "hill", cells: [82] },
    { shape: "diamond", cells: [67] },
  ],
};
