-- File generato da scripts/content-seed.ts: non modificare a mano.

insert into public.questions (id, category, level, kind, text, sheet_text, options) values ('tastes-001', 'tastes', 1, 'short', 'Qual è il mio piatto preferito?', 'Qual è il tuo piatto preferito?', null) on conflict (id) do update set category = excluded.category, level = excluded.level, kind = excluded.kind, text = excluded.text, sheet_text = excluded.sheet_text, options = excluded.options;
insert into public.questions (id, category, level, kind, text, sheet_text, options) values ('tastes-002', 'tastes', 1, 'multiple', 'Per una vacanza preferisco…', 'Per una vacanza preferisci…', '["Mare","Montagna","Città d''arte","Campagna"]'::jsonb) on conflict (id) do update set category = excluded.category, level = excluded.level, kind = excluded.kind, text = excluded.text, sheet_text = excluded.sheet_text, options = excluded.options;
insert into public.questions (id, category, level, kind, text, sheet_text, options) values ('tastes-003', 'tastes', 1, 'open', 'Qual è una canzone che ti fa pensare a noi, e perché?', null, null) on conflict (id) do update set category = excluded.category, level = excluded.level, kind = excluded.kind, text = excluded.text, sheet_text = excluded.sheet_text, options = excluded.options;
insert into public.questions (id, category, level, kind, text, sheet_text, options) values ('memories-001', 'memories', 1, 'short', 'Dove ci siamo dati il primo bacio?', 'Dove vi siete dati il primo bacio?', null) on conflict (id) do update set category = excluded.category, level = excluded.level, kind = excluded.kind, text = excluded.text, sheet_text = excluded.sheet_text, options = excluded.options;
insert into public.questions (id, category, level, kind, text, sheet_text, options) values ('future-001', 'future', 1, 'short', 'Dove vorrei vivere tra dieci anni?', 'Dove vorresti vivere tra dieci anni?', null) on conflict (id) do update set category = excluded.category, level = excluded.level, kind = excluded.kind, text = excluded.text, sheet_text = excluded.sheet_text, options = excluded.options;
insert into public.questions (id, category, level, kind, text, sheet_text, options) values ('deep-001', 'deep', 2, 'short', 'Di cosa ho più paura?', 'Di cosa hai più paura?', null) on conflict (id) do update set category = excluded.category, level = excluded.level, kind = excluded.kind, text = excluded.text, sheet_text = excluded.sheet_text, options = excluded.options;
insert into public.questions (id, category, level, kind, text, sheet_text, options) values ('funny-001', 'funny', 1, 'short', 'Qual è la mia abitudine più strana?', 'Qual è la tua abitudine più strana?', null) on conflict (id) do update set category = excluded.category, level = excluded.level, kind = excluded.kind, text = excluded.text, sheet_text = excluded.sheet_text, options = excluded.options;

insert into public.challenges (id, data) values ('tic-tac-toe', '{"id":"tic-tac-toe","name":"Tris","category":"builtin","mode":"duel","verdict":"automatic","durationSeconds":{"min":60,"max":180},"instructions":"Tre in fila vince. In caso di pareggio si rigioca.","prize":3,"snakeFlash":false,"minigame":"tic-tac-toe"}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.challenges (id, data) values ('funny-face', '{"id":"funny-face","name":"Faccia buffa","category":"videocall","mode":"trial","verdict":"judge","durationSeconds":{"min":30,"max":30},"instructions":"Fai la faccia più buffa che puoi: l''altro giudica se l''hai fatto ridere.","prize":2,"snakeFlash":true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.challenges (id, data) values ('lichess-blitz', '{"id":"lichess-blitz","name":"Lichess blitz 3 minuti","category":"external","mode":"duel","verdict":"double_confirm","durationSeconds":{"min":300,"max":480},"instructions":"Una partita blitz 3+0 su Lichess. Al ritorno dichiarate entrambi il vincitore.","prize":5,"snakeFlash":false,"url":"https://lichess.org/"}'::jsonb) on conflict (id) do update set data = excluded.data;

