import type { QuestionContent } from "../schema";

/**
 * Profonde — illustrazioni: specchio, rosa nella campana, serratura.
 * Unica categoria filtrata per livello in base alla casella (1-30 → 1, 31-70 → 2, 71-100 → 3).
 * 30 domande: 8 da scheda e 22 aperte, dieci per ognuno dei tre livelli (docs/content.md, F3-04).
 */
export const deep: QuestionContent[] = [
  {
    id: "deep-001",
    category: "deep",
    level: 2,
    kind: "short",
    text: "Di cosa ho più paura?",
    sheetText: "Di cosa hai più paura?",
  },
  {
    id: "deep-002",
    category: "deep",
    level: 1,
    kind: "short",
    text: "Qual è la cosa che mi fa sentire al sicuro?",
    sheetText: "Qual è la cosa che ti fa sentire al sicuro?",
  },
  {
    id: "deep-003",
    category: "deep",
    level: 1,
    kind: "multiple",
    text: "Quando sono in difficoltà preferisco…",
    sheetText: "Quando sei in difficoltà preferisci…",
    options: ["Parolarne subito", "Stare un po' in silenzio", "Distrarmi", "Fare una passeggiata"],
  },
  {
    id: "deep-004",
    category: "deep",
    level: 1,
    kind: "multiple",
    text: "Per stare bene mi serve soprattutto…",
    sheetText: "Per stare bene ti serve soprattutto…",
    options: ["Dormire bene", "Vedere gente", "Stare da solo", "Muovermi"],
  },
  {
    id: "deep-005",
    category: "deep",
    level: 2,
    kind: "short",
    text: "Qual è la cosa che mi fa arrabbiare davvero?",
    sheetText: "Qual è la cosa che ti fa arrabbiare davvero?",
  },
  {
    id: "deep-006",
    category: "deep",
    level: 2,
    kind: "multiple",
    text: "Dopo una giornata pesante mi aiuta…",
    sheetText: "Dopo una giornata pesante ti aiuta…",
    options: ["Un abbraccio", "Una doccia lunghissima", "Mangiare qualcosa di buono", "Dormire"],
  },
  {
    id: "deep-007",
    category: "deep",
    level: 3,
    kind: "short",
    text: "Qual è la cosa che mi commuove più facilmente?",
    sheetText: "Qual è la cosa che ti commuove più facilmente?",
  },
  {
    id: "deep-008",
    category: "deep",
    level: 3,
    kind: "short",
    text: "Di che cosa ho bisogno quando mi sento solo?",
    sheetText: "Di che cosa hai bisogno quando ti senti solo?",
  },
  {
    id: "deep-009",
    category: "deep",
    level: 1,
    kind: "open",
    text: "Raccontami che cosa ti fa sentire davvero ascoltato.",
  },
  {
    id: "deep-010",
    category: "deep",
    level: 1,
    kind: "open",
    text: "Qual è la cosa che ti dà energia quando sei stanco di tutto?",
  },
  {
    id: "deep-011",
    category: "deep",
    level: 1,
    kind: "open",
    text: "Raccontami un momento in cui ti sei sentito fuori posto, e come te ne sei andato.",
  },
  {
    id: "deep-012",
    category: "deep",
    level: 1,
    kind: "open",
    text: "Che cosa ti aiuta a ricominciare dopo una giornata storta?",
  },
  {
    id: "deep-013",
    category: "deep",
    level: 1,
    kind: "open",
    text: "Qual è la cosa di te che ancora non sai spiegare bene agli altri?",
  },
  {
    id: "deep-014",
    category: "deep",
    level: 1,
    kind: "open",
    text: "Raccontami un piccolo gesto che per te vale più di un regalo.",
  },
  {
    id: "deep-015",
    category: "deep",
    level: 1,
    kind: "open",
    text: "Che cosa ti fa sentire dentro un gruppo, invece di fuori?",
  },
  {
    id: "deep-016",
    category: "deep",
    level: 2,
    kind: "open",
    text: "Raccontami una cosa che hai cambiato di te negli ultimi anni e di cui sei contento.",
  },
  {
    id: "deep-017",
    category: "deep",
    level: 2,
    kind: "open",
    text: "Qual è la mia parte che ti fa tenerezza, e quando l'hai notata?",
  },
  {
    id: "deep-018",
    category: "deep",
    level: 2,
    kind: "open",
    text: "Raccontami un momento in cui hai faticato a dire la verità e poi l'hai detta.",
  },
  {
    id: "deep-019",
    category: "deep",
    level: 2,
    kind: "open",
    text: "Che cosa ti serve da me quando non stai bene, anche se non lo chiedi?",
  },
  {
    id: "deep-020",
    category: "deep",
    level: 2,
    kind: "open",
    text: "Qual è la cosa per cui ti senti più grato nella tua vita di adesso?",
  },
  {
    id: "deep-021",
    category: "deep",
    level: 2,
    kind: "open",
    text: "Raccontami come capisci che stai bene davvero con una persona.",
  },
  {
    id: "deep-022",
    category: "deep",
    level: 2,
    kind: "open",
    text: "Che cosa hai bisogno di sentirti dire ogni tanto, e chi dovrebbe dirtelo?",
  },
  {
    id: "deep-023",
    category: "deep",
    level: 3,
    kind: "open",
    text: "Raccontami la cosa più delicata che ti porti dentro e che dici a pochissime persone.",
  },
  {
    id: "deep-024",
    category: "deep",
    level: 3,
    kind: "open",
    text: "Qual è la parte di te che mostri solo quando ti fidi davvero?",
  },
  {
    id: "deep-025",
    category: "deep",
    level: 3,
    kind: "open",
    text: "Raccontami un momento in cui ti sei sentito piccolo, e che cosa ti ha fatto bene.",
  },
  {
    id: "deep-026",
    category: "deep",
    level: 3,
    kind: "open",
    text: "Che cosa vorresti che io capissi di te anche senza spiegazioni?",
  },
  {
    id: "deep-027",
    category: "deep",
    level: 3,
    kind: "open",
    text: "Raccontami di una volta in cui ti sei sentito profondamente felice e non l'hai detto a nessuno.",
  },
  {
    id: "deep-028",
    category: "deep",
    level: 3,
    kind: "open",
    text: "Qual è la cosa che ti fa più male a cui nessuno pensa?",
  },
  {
    id: "deep-029",
    category: "deep",
    level: 3,
    kind: "open",
    text: "Raccontami che cosa ti fa sentire libero, anche per pochi minuti.",
  },
  {
    id: "deep-030",
    category: "deep",
    level: 3,
    kind: "open",
    text: "Che cosa vorresti dire di noi due a chi ci vuole bene e non lo sa ancora?",
  },
];
