import type { QuestionContent } from "../schema";

/**
 * Buffe — illustrazioni: occhio, spazzolino, dado, mela.
 * 30 domande: 8 da scheda (scelta multipla o risposta breve) e 22 aperte (docs/content.md, F3-04).
 */
export const funny: QuestionContent[] = [
  {
    id: "funny-001",
    category: "funny",
    level: 1,
    kind: "short",
    text: "Qual è la mia abitudine più strana?",
    sheetText: "Qual è la tua abitudine più strana?",
  },
  {
    id: "funny-002",
    category: "funny",
    level: 1,
    kind: "multiple",
    text: "La mia colazione tipica è…",
    sheetText: "La tua colazione tipica è…",
    options: ["Solo caffè", "Dolce", "Salata", "Non faccio colazione"],
  },
  {
    id: "funny-003",
    category: "funny",
    level: 1,
    kind: "short",
    text: "Qual è la parola che dico più spesso?",
    sheetText: "Qual è la parola che dici più spesso?",
  },
  {
    id: "funny-004",
    category: "funny",
    level: 1,
    kind: "multiple",
    text: "Il mio talento inutile è…",
    sheetText: "Il tuo talento inutile è…",
    options: ["Imitare le voci", "Ricordare i numeri", "Cucinare a occhio", "Ballare male"],
  },
  {
    id: "funny-005",
    category: "funny",
    level: 2,
    kind: "short",
    text: "Qual è la mia mania più evidente?",
    sheetText: "Qual è la tua mania più evidente?",
  },
  {
    id: "funny-006",
    category: "funny",
    level: 2,
    kind: "multiple",
    text: "Quando sono annoiato finisco per…",
    sheetText: "Quando sei annoiato finisci per…",
    options: ["Guardare il telefono", "Riordinare", "Fare spuntini", "Dormire"],
  },
  {
    id: "funny-007",
    category: "funny",
    level: 2,
    kind: "short",
    text: "Qual è la cosa più assurda che ho comprato?",
    sheetText: "Qual è la cosa più assurda che hai comprato?",
  },
  {
    id: "funny-008",
    category: "funny",
    level: 2,
    kind: "multiple",
    text: "Se fossi un animale in casa sarei…",
    sheetText: "Se fossi un animale in casa saresti…",
    options: ["Gatto", "Cane", "Pappagallo", "Riccio"],
  },
  {
    id: "funny-009",
    category: "funny",
    level: 1,
    kind: "open",
    text: "Raccontami la figuraccia più divertente che ti ricordi di aver fatto con me davanti.",
  },
  {
    id: "funny-010",
    category: "funny",
    level: 1,
    kind: "open",
    text: "Qual è la cosa più stupida che abbiamo comprato insieme, e quanto l'abbiamo usata?",
  },
  {
    id: "funny-011",
    category: "funny",
    level: 1,
    kind: "open",
    text: "Raccontami un momento in cui hai riso così tanto da non riuscire a parlare.",
  },
  {
    id: "funny-012",
    category: "funny",
    level: 1,
    kind: "open",
    text: "Qual è la scusa più creativa che hai usato per non fare qualcosa?",
  },
  {
    id: "funny-013",
    category: "funny",
    level: 1,
    kind: "open",
    text: "Raccontami la tua teoria più assurda su come funziona il mondo.",
  },
  {
    id: "funny-014",
    category: "funny",
    level: 1,
    kind: "open",
    text: "Qual è la cosa che ti fa ridere ancora adesso, anche solo ripensandoci?",
  },
  {
    id: "funny-015",
    category: "funny",
    level: 1,
    kind: "open",
    text: "Raccontami un episodio in cucina che poteva finire male e che ora raccontiamo ridendo.",
  },
  {
    id: "funny-016",
    category: "funny",
    level: 2,
    kind: "open",
    text: "Qual è la tua abitudine più imbarazzante quando sei da solo in casa?",
  },
  {
    id: "funny-017",
    category: "funny",
    level: 2,
    kind: "open",
    text: "Raccontami una volta in cui hai fatto finta di sapere una cosa e non la sapevi affatto.",
  },
  {
    id: "funny-018",
    category: "funny",
    level: 2,
    kind: "open",
    text: "Qual è il soprannome più brutto che ti hanno dato, e chi te l'ha dato?",
  },
  {
    id: "funny-019",
    category: "funny",
    level: 2,
    kind: "open",
    text: "Raccontami una scena che ti è sembrata normalissima e che gli altri hanno trovato stranissima.",
  },
  {
    id: "funny-020",
    category: "funny",
    level: 2,
    kind: "open",
    text: "Che cosa faresti se per un giorno potessi essere invisibile senza conseguenze?",
  },
  {
    id: "funny-021",
    category: "funny",
    level: 2,
    kind: "open",
    text: "Raccontami la tua versione preferita delle cose che diciamo sempre per scherzo.",
  },
  {
    id: "funny-022",
    category: "funny",
    level: 2,
    kind: "open",
    text: "Qual è la cosa che ti fa venire voglia di ballare anche se non c'è musica?",
  },
  {
    id: "funny-023",
    category: "funny",
    level: 3,
    kind: "open",
    text: "Raccontami una cosa di me che ti fa ridere e che non ho mai capito di fare.",
  },
  {
    id: "funny-024",
    category: "funny",
    level: 3,
    kind: "open",
    text: "Qual è il tuo piano segreto più ridicolo, quello che funzionerebbe solo nella tua testa?",
  },
  {
    id: "funny-025",
    category: "funny",
    level: 3,
    kind: "open",
    text: "Raccontami che cosa diresti in un discorso di ringraziamento per un premio che non hai vinto.",
  },
  {
    id: "funny-026",
    category: "funny",
    level: 3,
    kind: "open",
    text: "Qual è la cosa più tenera e insieme più ridicola che hai fatto per farmi contento?",
  },
  {
    id: "funny-027",
    category: "funny",
    level: 3,
    kind: "open",
    text: "Raccontami come reagiresti se domani ti svegliassi con la mia voce.",
  },
  {
    id: "funny-028",
    category: "funny",
    level: 3,
    kind: "open",
    text: "Qual è la cosa che faresti se non avessi paura di sembrare stupido?",
  },
  {
    id: "funny-029",
    category: "funny",
    level: 3,
    kind: "open",
    text: "Raccontami il titolo del film che racconterebbe la nostra serata di oggi.",
  },
  {
    id: "funny-030",
    category: "funny",
    level: 3,
    kind: "open",
    text: "Che cosa ti piacerebbe mi restasse impresso come la tua battuta migliore?",
  },
];
