import type { QuestionContent } from "../schema";

/**
 * Futuro — illustrazioni: anello, casa, gabbia aperta, mappa.
 * 30 domande: 8 da scheda (scelta multipla o risposta breve) e 22 aperte (docs/content.md, F3-04).
 */
export const future: QuestionContent[] = [
  {
    id: "future-001",
    category: "future",
    level: 1,
    kind: "short",
    text: "Dove vorrei vivere tra dieci anni?",
    sheetText: "Dove vorresti vivere tra dieci anni?",
  },
  {
    id: "future-002",
    category: "future",
    level: 1,
    kind: "multiple",
    text: "La casa dei miei sogni è…",
    sheetText: "La casa dei tuoi sogni è…",
    options: ["In centro", "In campagna", "Al mare", "All'estero"],
  },
  {
    id: "future-003",
    category: "future",
    level: 1,
    kind: "short",
    text: "Qual è il mio lavoro ideale fra dieci anni?",
    sheetText: "Qual è il tuo lavoro ideale fra dieci anni?",
  },
  {
    id: "future-004",
    category: "future",
    level: 1,
    kind: "multiple",
    text: "Il prossimo viaggio che sogno è…",
    sheetText: "Il prossimo viaggio che sogni è…",
    options: ["In Asia", "In America", "In un posto freddo", "In un posto vicino"],
  },
  {
    id: "future-005",
    category: "future",
    level: 2,
    kind: "short",
    text: "Qual è la prima cosa che vorrei comprare appena posso?",
    sheetText: "Qual è la prima cosa che vorresti comprare appena puoi?",
  },
  {
    id: "future-006",
    category: "future",
    level: 2,
    kind: "multiple",
    text: "Fra cinque anni mi vedo più…",
    sheetText: "Fra cinque anni ti vedi più…",
    options: [
      "Con un progetto nuovo",
      "Con più tempo libero",
      "Con una casa nostra",
      "Con più viaggi alle spalle",
    ],
  },
  {
    id: "future-007",
    category: "future",
    level: 2,
    kind: "short",
    text: "Qual è la città dove mi piacerebbe trasferirmi?",
    sheetText: "Qual è la città dove ti piacerebbe trasferirti?",
  },
  {
    id: "future-008",
    category: "future",
    level: 2,
    kind: "multiple",
    text: "Se potessi imparare una cosa nuova da zero, sceglierei…",
    sheetText: "Se potessi imparare una cosa nuova da zero, sceglieresti…",
    options: ["Una lingua", "Uno strumento", "Uno sport", "Un mestiere manuale"],
  },
  {
    id: "future-009",
    category: "future",
    level: 1,
    kind: "open",
    text: "Raccontami la giornata tipo che vorresti avere fra dieci anni, dall'alba alla sera.",
  },
  {
    id: "future-010",
    category: "future",
    level: 1,
    kind: "open",
    text: "Che cosa vorresti aver imparato a fare bene, e perché non hai ancora cominciato?",
  },
  {
    id: "future-011",
    category: "future",
    level: 1,
    kind: "open",
    text: "Qual è il posto in cui ti piacerebbe portarmi almeno una volta nella vita?",
  },
  {
    id: "future-012",
    category: "future",
    level: 1,
    kind: "open",
    text: "Se potessi lavorare da qualunque posto, dove apriresti il portatile domani mattina?",
  },
  {
    id: "future-013",
    category: "future",
    level: 1,
    kind: "open",
    text: "Raccontami un progetto che ti piacerebbe cominciare quest'anno e che rimandi sempre.",
  },
  {
    id: "future-014",
    category: "future",
    level: 2,
    kind: "open",
    text: "Come immagini la casa in cui vorresti invecchiare: stanze, luce, rumori?",
  },
  {
    id: "future-015",
    category: "future",
    level: 2,
    kind: "open",
    text: "Qual è la tradizione che vorresti cominciare con me e tenere per anni?",
  },
  {
    id: "future-016",
    category: "future",
    level: 2,
    kind: "open",
    text: "Raccontami che cosa vorresti che facessimo insieme quando avremo entrambi più tempo.",
  },
  {
    id: "future-017",
    category: "future",
    level: 2,
    kind: "open",
    text: "Qual è la cosa che vorresti riuscire a fare senza più rimandarla?",
  },
  {
    id: "future-018",
    category: "future",
    level: 2,
    kind: "open",
    text: "Raccontami come immagini la nostra estate perfetta, quella che vorresti ripetere ogni anno.",
  },
  {
    id: "future-019",
    category: "future",
    level: 2,
    kind: "open",
    text: "Che cosa vorresti ci fosse scritto di noi fra vent'anni, in una riga sola?",
  },
  {
    id: "future-020",
    category: "future",
    level: 2,
    kind: "open",
    text: "Qual è il desiderio che non hai mai detto ad alta voce per scaramanzia?",
  },
  {
    id: "future-021",
    category: "future",
    level: 2,
    kind: "open",
    text: "Raccontami il modo in cui vorresti festeggiare un traguardo importante fra qualche anno.",
  },
  {
    id: "future-022",
    category: "future",
    level: 3,
    kind: "open",
    text: "Che cosa vuoi che resti di noi due, qualunque cosa succeda?",
  },
  {
    id: "future-023",
    category: "future",
    level: 3,
    kind: "open",
    text: "Raccontami la versione di te che vorresti diventare per stare meglio con me.",
  },
  {
    id: "future-024",
    category: "future",
    level: 3,
    kind: "open",
    text: "Qual è la cosa di me che vorresti non cambiasse mai, negli anni?",
  },
  {
    id: "future-025",
    category: "future",
    level: 3,
    kind: "open",
    text: "Raccontami che cosa hai paura di non riuscire a costruire insieme.",
  },
  {
    id: "future-026",
    category: "future",
    level: 3,
    kind: "open",
    text: "Se dovessi darci un consiglio guardandoci fra dieci anni, quale sarebbe?",
  },
  {
    id: "future-027",
    category: "future",
    level: 3,
    kind: "open",
    text: "Raccontami come vorresti che ci ricordassero le persone che ci vogliono bene.",
  },
  {
    id: "future-028",
    category: "future",
    level: 3,
    kind: "open",
    text: "Qual è il sogno che hai messo da parte per stare in una vita insieme?",
  },
  {
    id: "future-029",
    category: "future",
    level: 3,
    kind: "open",
    text: "Raccontami che cosa vorresti dirmi fra dieci anni, ripensando a stasera.",
  },
  {
    id: "future-030",
    category: "future",
    level: 3,
    kind: "open",
    text: "Qual è la promessa che vorresti farti più che farmi?",
  },
];
