import type { QuestionContent } from "../schema";

/**
 * Ricordi — illustrazioni: lettera, cornice, macchina da scrivere, telefono.
 * 30 domande: 8 da scheda (scelta multipla o risposta breve) e 22 aperte (docs/content.md, F3-04).
 */
export const memories: QuestionContent[] = [
  {
    id: "memories-001",
    category: "memories",
    level: 1,
    kind: "short",
    text: "Dove ci siamo dati il primo bacio?",
    sheetText: "Dove vi siete dati il primo bacio?",
  },
  {
    id: "memories-002",
    category: "memories",
    level: 1,
    kind: "multiple",
    text: "La prima volta che ci siamo visti eravamo…",
    sheetText: "La prima volta che vi siete visti eravate…",
    options: ["A cena fuori", "A casa di amici", "A una festa", "In un locale"],
  },
  {
    id: "memories-003",
    category: "memories",
    level: 1,
    kind: "short",
    text: "Qual è il mio primo ricordo di noi due?",
    sheetText: "Qual è il tuo primo ricordo di noi due?",
  },
  {
    id: "memories-004",
    category: "memories",
    level: 1,
    kind: "multiple",
    text: "Il nostro anniversario lo festeggiamo con…",
    sheetText: "Il vostro anniversario lo festeggiate con…",
    options: ["Cena fuori", "Un regalo", "Un viaggio", "Senza programmi"],
  },
  {
    id: "memories-005",
    category: "memories",
    level: 2,
    kind: "short",
    text: "Dove abbiamo dormito insieme la prima volta?",
    sheetText: "Dove avete dormito insieme la prima volta?",
  },
  {
    id: "memories-006",
    category: "memories",
    level: 2,
    kind: "multiple",
    text: "Il nostro primo litigio era su…",
    sheetText: "Il vostro primo litigio era su…",
    options: ["Cose pratiche", "Un fraintendimento", "Il tempo che ci diamo", "La gelosia"],
  },
  {
    id: "memories-007",
    category: "memories",
    level: 2,
    kind: "short",
    text: "Qual è stato il regalo che mi ha fatto più piacere?",
    sheetText: "Qual è stato il regalo che ti ha fatto più piacere?",
  },
  {
    id: "memories-008",
    category: "memories",
    level: 2,
    kind: "multiple",
    text: "La nostra prima vacanza insieme è stata…",
    sheetText: "La vostra prima vacanza insieme è stata…",
    options: ["Al mare", "In montagna", "In una città", "A due passi da casa"],
  },
  {
    id: "memories-009",
    category: "memories",
    level: 1,
    kind: "open",
    text: "Raccontami il giorno in cui ci siamo conosciuti: che cosa ti è rimasto in testa di me?",
  },
  {
    id: "memories-010",
    category: "memories",
    level: 1,
    kind: "open",
    text: "Qual è la foto di noi due che riguardi più spesso, e che cosa succedeva quel giorno?",
  },
  {
    id: "memories-011",
    category: "memories",
    level: 1,
    kind: "open",
    text: "Raccontami una serata qualunque diventata memorabile senza che ce ne accorgessimo.",
  },
  {
    id: "memories-012",
    category: "memories",
    level: 1,
    kind: "open",
    text: "Qual è la prima cosa che ti ho detto che ti ha fatto ridere?",
  },
  {
    id: "memories-013",
    category: "memories",
    level: 1,
    kind: "open",
    text: "Raccontami come immaginavi noi due prima di conoscerci davvero.",
  },
  {
    id: "memories-014",
    category: "memories",
    level: 2,
    kind: "open",
    text: "Qual è la giornata che racconteresti a chi ci chiede come è nata la nostra storia?",
  },
  {
    id: "memories-015",
    category: "memories",
    level: 2,
    kind: "open",
    text: "Raccontami il momento in cui hai capito che eravamo una cosa seria.",
  },
  {
    id: "memories-016",
    category: "memories",
    level: 2,
    kind: "open",
    text: "Qual è il posto dove torniamo sempre, e che cosa ci è successo lì?",
  },
  {
    id: "memories-017",
    category: "memories",
    level: 2,
    kind: "open",
    text: "Raccontami un viaggio in cui ci siamo persi davvero: che cosa abbiamo fatto?",
  },
  {
    id: "memories-018",
    category: "memories",
    level: 2,
    kind: "open",
    text: "Qual è una cosa che facevamo all'inizio e che non facciamo più, e ti piacerebbe rifare?",
  },
  {
    id: "memories-019",
    category: "memories",
    level: 2,
    kind: "open",
    text: "Raccontami la prima volta che hai parlato di me alla tua famiglia.",
  },
  {
    id: "memories-020",
    category: "memories",
    level: 2,
    kind: "open",
    text: "Qual è stata la sorpresa meglio riuscita che ci siamo fatti?",
  },
  {
    id: "memories-021",
    category: "memories",
    level: 2,
    kind: "open",
    text: "Raccontami un giorno difficile che abbiamo passato insieme e come ne siamo usciti.",
  },
  {
    id: "memories-022",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Qual è il momento in cui ti sei sentito più vicino a me, anche in silenzio?",
  },
  {
    id: "memories-023",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Raccontami qualcosa di noi che non hai mai detto a voce e che ti porti dentro.",
  },
  {
    id: "memories-024",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Qual è la mia versione di cui ti sei innamorato, e quando l'hai vista la prima volta?",
  },
  {
    id: "memories-025",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Raccontami un momento in cui hai avuto paura di perdermi.",
  },
  {
    id: "memories-026",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Qual è la cosa più tenera che hai pensato di me e non hai mai detto?",
  },
  {
    id: "memories-027",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Raccontami come ti sei immaginato la nostra vita fra dieci anni, la prima volta che ci hai pensato.",
  },
  {
    id: "memories-028",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Qual è il giorno in cui avresti voluto fermare il tempo, e perché proprio quello?",
  },
  {
    id: "memories-029",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Che cosa hai imparato su di te stando con me?",
  },
  {
    id: "memories-030",
    category: "memories",
    level: 3,
    kind: "open",
    text: "Raccontami una cosa che vorresti mi ricordassi di noi per sempre.",
  },
];
