import type { QuestionContent } from "../schema";

/**
 * Gusti — illustrazioni: bottiglia, calici, vinile, chitarra.
 * 30 domande: 8 da scheda (scelta multipla o risposta breve) e 22 aperte (docs/content.md, F3-04).
 */
export const tastes: QuestionContent[] = [
  {
    id: "tastes-001",
    category: "tastes",
    level: 1,
    kind: "short",
    text: "Qual è il mio piatto preferito?",
    sheetText: "Qual è il tuo piatto preferito?",
  },
  {
    id: "tastes-002",
    category: "tastes",
    level: 1,
    kind: "multiple",
    text: "Per una vacanza preferisco…",
    sheetText: "Per una vacanza preferisci…",
    options: ["Mare", "Montagna", "Città d'arte", "Campagna"],
  },
  {
    id: "tastes-003",
    category: "tastes",
    level: 1,
    kind: "open",
    text: "Qual è una canzone che ti fa pensare a noi, e perché?",
  },
  {
    id: "tastes-004",
    category: "tastes",
    level: 1,
    kind: "short",
    text: "Qual è la mia bevanda della domenica mattina?",
    sheetText: "Qual è la tua bevanda della domenica mattina?",
  },
  {
    id: "tastes-005",
    category: "tastes",
    level: 1,
    kind: "multiple",
    text: "La mia serata ideale è…",
    sheetText: "La tua serata ideale è…",
    options: ["Cinema", "Cena fuori", "Divano e serie", "Passeggiata"],
  },
  {
    id: "tastes-006",
    category: "tastes",
    level: 2,
    kind: "short",
    text: "Qual è il mio dolce preferito?",
    sheetText: "Qual è il tuo dolce preferito?",
  },
  {
    id: "tastes-007",
    category: "tastes",
    level: 2,
    kind: "multiple",
    text: "Per addormentarmi mi serve…",
    sheetText: "Per addormentarti ti serve…",
    options: ["Silenzio assoluto", "Un po' di rumore", "Musica o podcast", "Buio totale"],
  },
  {
    id: "tastes-008",
    category: "tastes",
    level: 2,
    kind: "short",
    text: "Qual è la mia canzone preferita degli ultimi anni?",
    sheetText: "Qual è la tua canzone preferita degli ultimi anni?",
  },
  {
    id: "tastes-009",
    category: "tastes",
    level: 2,
    kind: "multiple",
    text: "Quando scelgo la musica metto…",
    sheetText: "Quando scegli la musica metti…",
    options: ["Cantautorato italiano", "Roba internazionale", "Anni '80 e '90", "Solo strumentale"],
  },
  {
    id: "tastes-010",
    category: "tastes",
    level: 1,
    kind: "open",
    text: "Raccontami un pasto che ricorderesti per sempre: dove eravamo e che cosa abbiamo mangiato?",
  },
  {
    id: "tastes-011",
    category: "tastes",
    level: 1,
    kind: "open",
    text: "Qual è la cosa che ordini sempre al bar, e che cosa dice di te?",
  },
  {
    id: "tastes-012",
    category: "tastes",
    level: 1,
    kind: "open",
    text: "Qual è il posto più bello in cui abbiamo mangiato insieme, e perché proprio quello?",
  },
  {
    id: "tastes-013",
    category: "tastes",
    level: 1,
    kind: "open",
    text: "C'è un film che riguarderesti con me stasera? Raccontami perché.",
  },
  {
    id: "tastes-014",
    category: "tastes",
    level: 1,
    kind: "open",
    text: "Che cosa metti sul giradischi quando vuoi stare bene?",
  },
  {
    id: "tastes-015",
    category: "tastes",
    level: 2,
    kind: "open",
    text: "Qual è un gusto che hai scoperto grazie a noi due, e che prima non avresti mai provato?",
  },
  {
    id: "tastes-016",
    category: "tastes",
    level: 2,
    kind: "open",
    text: "Raccontami la tua colazione perfetta, minuto per minuto.",
  },
  {
    id: "tastes-017",
    category: "tastes",
    level: 2,
    kind: "open",
    text: "Qual è la canzone che hai ascoltato più volte quest'anno, e che periodo raccontava?",
  },
  {
    id: "tastes-018",
    category: "tastes",
    level: 2,
    kind: "open",
    text: "Se dovessimo aprire un locale insieme, che cosa serviremmo e come si chiamerebbe?",
  },
  {
    id: "tastes-019",
    category: "tastes",
    level: 2,
    kind: "open",
    text: 'Qual è la cosa che ti fa dire "questa serata è andata bene"?',
  },
  {
    id: "tastes-020",
    category: "tastes",
    level: 2,
    kind: "open",
    text: "Raccontami un viaggio che rifaresti identico, tappa per tappa.",
  },
  {
    id: "tastes-021",
    category: "tastes",
    level: 2,
    kind: "open",
    text: "Che cosa guardi quando non hai voglia di pensare a niente?",
  },
  {
    id: "tastes-022",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Qual è il modo in cui mi prendi quando sono di cattivo umore?",
  },
  {
    id: "tastes-023",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Qual è un piccolo lusso che ti concedi e che non racconti a nessuno?",
  },
  {
    id: "tastes-024",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Che cosa ti fa sentire a casa più di qualunque altro posto?",
  },
  {
    id: "tastes-025",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Qual è la cosa più dolce che ti hanno detto, e chi te l'ha detta?",
  },
  {
    id: "tastes-026",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Raccontami un momento in cui ti sei sentito davvero fiero di noi due.",
  },
  {
    id: "tastes-027",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Qual è la cosa che ti manca di più del nostro primo anno insieme?",
  },
  {
    id: "tastes-028",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Se dovessi descrivermi a una persona che non mi ha mai visto, da dove partiresti?",
  },
  {
    id: "tastes-029",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Che cosa ti fa ridere di me anche quando non vorresti ridere?",
  },
  {
    id: "tastes-030",
    category: "tastes",
    level: 3,
    kind: "open",
    text: "Qual è la promessa più bella che ti piacerebbe ci facessimo?",
  },
];
