import { challengeSchema, type ChallengeContent } from "./schema";

/**
 * Carte sfida (task F4-01). Aggiungere una sfida = aggiungere un oggetto qui.
 *
 * Vincoli (docs/content.md, `challengeSchema`): prova ⇒ verdetto `judge`; duello ⇒ `automatic` (con `minigame`)
 * oppure `double_confirm`; sfida lampo ⇒ durata massima 30 secondi; sfida esterna ⇒ `url`.
 *
 * `quiz-lampo` e `riflessi` sono minigiochi a tempo del motore (task F4-04, D-55): il quiz porta le sue
 * domande nel campo `quiz` (contenuto pubblico, non la scheda), i riflessi non hanno bisogno di contenuti.
 */
const raw: ChallengeContent[] = [
  // --- Integrati ---------------------------------------------------------
  {
    id: "tic-tac-toe",
    name: "Tris",
    category: "builtin",
    mode: "duel",
    verdict: "automatic",
    durationSeconds: { min: 60, max: 180 },
    instructions: "Tre in fila vince. In caso di pareggio si rigioca.",
    prize: 3,
    snakeFlash: false,
    minigame: "tic-tac-toe",
  },
  {
    id: "connect-four",
    name: "Forza 4",
    category: "builtin",
    mode: "duel",
    verdict: "automatic",
    durationSeconds: { min: 90, max: 240 },
    instructions: "Quattro pedine in fila, in orizzontale, verticale o diagonale. Pareggio: si rigioca.",
    prize: 3,
    snakeFlash: false,
    minigame: "connect-four",
  },
  {
    id: "memory",
    name: "Memory",
    category: "builtin",
    mode: "duel",
    verdict: "automatic",
    durationSeconds: { min: 90, max: 240 },
    instructions: "Dodici carte, sei coppie: chi ne trova di più vince. In caso di pareggio si rigioca.",
    prize: 3,
    snakeFlash: false,
    minigame: "memory",
  },
  {
    id: "quiz-lampo",
    name: "Quiz a tempo",
    category: "builtin",
    mode: "duel",
    verdict: "automatic",
    durationSeconds: { min: 60, max: 120 },
    instructions:
      "Cinque domande a risposta rapida, a turno, con i secondi che scorrono: chi risponde giusto a più domande vince. In caso di pareggio si rigioca.",
    prize: 3,
    snakeFlash: false,
    minigame: "quiz",
    quiz: [
      {
        question: "Quante corde ha una chitarra classica?",
        options: ["Quattro", "Sei", "Otto"],
        correct: 1,
      },
      {
        question: "In quale città si trova la Torre Eiffel?",
        options: ["Parigi", "Lione", "Marsiglia"],
        correct: 0,
      },
      {
        question: "Qual è il pianeta più vicino al Sole?",
        options: ["Venere", "Mercurio", "Marte"],
        correct: 1,
      },
      {
        question: "Quante ore dura un giorno?",
        options: ["Dodici", "Ventiquattro", "Trentasei"],
        correct: 1,
      },
      {
        question: "Chi ha dipinto la Gioconda?",
        options: ["Leonardo da Vinci", "Michelangelo", "Raffaello"],
        correct: 0,
      },
    ],
  },
  {
    id: "riflessi",
    name: "Riflessi",
    category: "builtin",
    mode: "duel",
    verdict: "automatic",
    durationSeconds: { min: 60, max: 120 },
    instructions:
      "Un segnale parte a sorpresa, il primo che lo tocca prende il punto: si gioca al meglio di cinque. Chi tocca troppo presto regala il punto all'altro.",
    prize: 3,
    snakeFlash: false,
    minigame: "reflex",
  },

  // --- Videochiamata -----------------------------------------------------
  {
    id: "funny-face",
    name: "Faccia buffa",
    category: "videocall",
    mode: "trial",
    verdict: "judge",
    durationSeconds: { min: 30, max: 30 },
    instructions: "Fai la faccia più buffa che puoi: l'altro giudica se l'hai fatto ridere.",
    prize: 2,
    snakeFlash: true,
  },
  {
    id: "mimo",
    name: "Mimo in 30 secondi",
    category: "videocall",
    mode: "trial",
    verdict: "judge",
    durationSeconds: { min: 30, max: 30 },
    instructions: "Fai indovinare una scena di film solo con i gesti. L'altro giudica se ci sei riuscito.",
    prize: 2,
    snakeFlash: true,
  },
  {
    id: "oggetto-in-20-secondi",
    name: "Trova l'oggetto",
    category: "videocall",
    mode: "trial",
    verdict: "judge",
    durationSeconds: { min: 20, max: 20 },
    instructions: "Porta davanti alla webcam l'oggetto chiesto dall'altro entro 20 secondi.",
    prize: 2,
    snakeFlash: true,
  },
  {
    id: "accento-straniero",
    name: "Accento straniero",
    category: "videocall",
    mode: "trial",
    verdict: "judge",
    durationSeconds: { min: 30, max: 30 },
    instructions: "Racconta la tua giornata con un accento a scelta: l'altro giudica se l'accento tiene.",
    prize: 2,
    snakeFlash: true,
  },
  {
    id: "imitazione-cantante",
    name: "Imitazione",
    category: "videocall",
    mode: "trial",
    verdict: "judge",
    durationSeconds: { min: 30, max: 30 },
    instructions: "Impersona un cantante per trenta secondi: l'altro giudica se si capisce chi è.",
    prize: 2,
    snakeFlash: true,
  },
  {
    id: "scioglilingua",
    name: "Scioglilingua",
    category: "videocall",
    mode: "trial",
    verdict: "judge",
    durationSeconds: { min: 30, max: 30 },
    instructions: "Ripeti tre volte di fila uno scioglilingua scelto dall'altro senza inciampare.",
    prize: 2,
    snakeFlash: true,
  },
  {
    id: "tre-parole",
    name: "Storia in tre parole",
    category: "videocall",
    mode: "trial",
    verdict: "judge",
    durationSeconds: { min: 60, max: 60 },
    instructions: "L'altro sceglie tre parole: racconta una storia di un minuto che le contenga tutte.",
    prize: 2,
    snakeFlash: false,
  },
  {
    id: "indovina-la-canzone",
    name: "Indovina la canzone",
    category: "videocall",
    mode: "duel",
    verdict: "double_confirm",
    durationSeconds: { min: 90, max: 120 },
    instructions:
      "A turno canticchiate un pezzo a bocca chiusa: chi indovina per primo vince il punto, si gioca al meglio di cinque. Dichiarate entrambi il risultato.",
    prize: 3,
    snakeFlash: false,
  },
  {
    id: "karaoke-a-due",
    name: "Karaoke a due",
    category: "videocall",
    mode: "duel",
    verdict: "double_confirm",
    durationSeconds: { min: 120, max: 180 },
    instructions:
      "Cantate insieme un ritornello, ognuno per conto suo: al ritorno dichiarate entrambi chi ha tenuto meglio la tonalità.",
    prize: 3,
    snakeFlash: false,
  },
  {
    id: "sfida-foto",
    name: "Foto uguale",
    category: "videocall",
    mode: "trial",
    verdict: "judge",
    durationSeconds: { min: 45, max: 45 },
    instructions: "L'altro sceglie una foto di voi due: ricrea la posa in 45 secondi e mostra il risultato.",
    prize: 2,
    snakeFlash: false,
  },

  // --- Siti esterni ------------------------------------------------------
  {
    id: "lichess-blitz",
    name: "Lichess blitz 3 minuti",
    category: "external",
    mode: "duel",
    verdict: "double_confirm",
    durationSeconds: { min: 300, max: 480 },
    instructions: "Una partita blitz 3+0 su Lichess. Al ritorno dichiarate entrambi il vincitore.",
    prize: 5,
    snakeFlash: false,
    url: "https://lichess.org/",
  },
  {
    id: "skribblio",
    name: "Skribbl.io",
    category: "external",
    mode: "duel",
    verdict: "double_confirm",
    durationSeconds: { min: 300, max: 600 },
    instructions:
      "Una partita a skribbl.io con le impostazioni di base: al ritorno dichiarate entrambi chi ha fatto più punti.",
    prize: 5,
    snakeFlash: false,
    url: "https://skribbl.io/",
  },
];

export const challenges: ChallengeContent[] = raw.map((challenge) => challengeSchema.parse(challenge));
